apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-deploym
  name: my-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    nodePort: 31000
  selector:
    app: my-deploym
  
  type: NodePort


